parameters:
#    stc_venue.example.class: Stc\Bundle\VenueBundle\Example

services:
#    stc_venue.example:
#        class: %stc_venue.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
